name: Deploy Dev Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: install dependencies
      run: npm ci
    - name: Serverless Deploy
      run: npm run deploy:dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_SIGNING_SECRET: ${{ secrets.ZORGBORT_STAGE_SLACK_SIGNING_SECRET }}
        SLACK_BOT_TOKEN: ${{ secrets.ZORGBORT_STAGE_SLACK_BOT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.ZORGBORT_TOKEN }}
        VALID_RELEASE_USERS: ${{ secrets.ZORGBORT_STAGE_VALID_RELEASE_USERS }}
