name: Deploy Production Build

on:
  push:
    tags:
      - '*'

concurrency: deploy-prod

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install dependencies
      run: npm ci
    - name: Serverless Deploy
      run: npm run deploy:production
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_SIGNING_SECRET: ${{ secrets.ZORGBORT_SLACK_SIGNING_SECRET }}
        SLACK_BOT_TOKEN: ${{ secrets.ZORGBORT_SLACK_BOT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.ZORGBORT_TOKEN }}
        VALID_RELEASE_USERS: ${{ secrets.ZORGBORT_VALID_RELEASE_USERS }}
