name: Tag Version

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.ZORGBORT_TOKEN }}
    - name: Setup Git
      run: |
        git config --global user.name "Zorgbort"
        git config --global user.email "info@iliosproject.org"
    - name: Increment Version
      run: npm version major
    - name: Push Changes
      run: git push --follow-tags